name: Java build
"on": [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ 8, 8.0.192, 9.0.x, 10, 11.0.x, 11.0.3, 12, 13 ]
    name: Java ${{ matrix.java }} Build
    steps:
      - name: Linux kernel version check
        run: uname -a
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: ./gradlew build